language: node_js

cache:
  - npm
  - cargo

os:
  - osx
  - linux
  - windows

node_js:
  - "14"
  - "12"
  - "10"

install:
  - curl https://sh.rustup.rs -sSf > /tmp/rustup.sh
  - sh /tmp/rustup.sh -y
  - export PATH="$HOME/.cargo/bin:$PATH"
  - source "$HOME/.cargo/env"
  - npm install

before_script:
  - npm run build

deploy:
  provider: script
  script: npm run upload-binary
  edge: true
  cleanup: false
  on:
    tags: true
